#!/usr/bin/env php
<?php

    if ($argc != 2)
    {
        print ("Import path to file.\n");
        return -1;
    }
    
    $filename = $argv[1];
    
    if (!file_exists($filename))
    {
        print("Error: " . $filename . " doesn't exist.\n");
        return -1;
    }
    
    if (!is_readable($filename))
    {
        print("Error: " . $filename . " is not readable.\n");
        return -1;
    }
    
    // Open US.text
    $file = fopen("$filename", "r");
    
    if (!$file)
    {
        print("Error: Unable to open " . $file . ".\n");
        return -1;
    }
    
    // Import file into database
    $currLine = 1;
    $errCount = 0;
    
    // Iterate through file
    while (($row = fgets($file, 1000)) !== FALSE) 
    {   
        // Put columns into array
        list($country_code, $postal_code, $place_name, $admin_name1, $admin_code1, $admin_name2, $admin_code2, $admin_name3, $admin_code3, $latitude, $longitude, $accuracy) = explode("\t", $row);
    
    
        $result = query("INSERT INTO places(country_code, postal_code, place_name, admin_name1, admin_code1, admin_name2, admin_code2, admin_name3, admin_code3, latitude, longitude, accuracy)
        VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", $country_code, $postal_code, $place_name, $admin_name1, $admin_code1, $admin_name2, $admin_code2, $admin_name3, $admin_code3, $latitude, $longitude, $accuracy);
        
        if ($result === false)
        {
            print("Error insterting line " . $currLine . "\n");
            $errCount++;
        }
        
        $currLine++;
    }
    
    // Display results
    print("File successfully imported:\nLines read: " . $currLine . "\nErrors: " . $errCount . "\n");
    
    fclose($file);

?>

